apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka-lb
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: nikolai97/doctor-appointment-discovery-server:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: EUREKA_SERVER_ADDRESS
  replicas: 1
